Statement1 <-"HDM Builder chaitali sawant"
Statement2 <- "Model Name"
Statement3 <- "The name of your model"
Statement4 <- "Decision"
Statement5 <- "Whatever you're trying to decide"
Statement6 <- "Criteria"
Statement7 <- "i.e.) criteria1,2, etc"
Statement8 <- "Alternatives"
Statement9 <- "i.e.) alternative 1, 2, etc"
Statement10 <- "Update Alternatives"
Statement11 <- "My Models"
Statement12 <- "Enter your email and make up a pin so anything you save gets associated to you."
Statement13 <- "Email"
Statement14 <- "ex: you@domain.com"
Statement15 <- "Pin"
Statement16 <-"4 digit pin, ex: 1234"
Statement17 <-"Load my models"
Statement18 <- "List of all previous models"
Statement19 <-"Model Designer"
Statement20 <- "Decision Tree"
Statement21 <-"Save Model"
Statement22 <- "Rebuild Tree From Form"
Statement23 <- "Load Example"
Statement24 <- "Alternatives"
Statement25 <- "Experts"
Statement26 <- "Add or remove experts here"
Statement27 <- "After you've saved your model you can add some experts. Each expert will have a specific URL where they will rate your model,if you need to manually send a URL make sure to use the correct one."
Statement28 <- "New Expert"
Statement29 <- "enter email here..."
Statement30 <- "Update Experts"
Statement31 <- "Add New"
Statement32 <- "Evaluation Form"
Statement33 <- "This is the form your experts will fill out"
Statement34 <- "Your experts will see a form like this, you don't have to do anything here."
Statement35 <- "Results"
Statement36 <- "Load Results"
Statement37 <- "Instructions"
Statement38 <- "Welcome to the HDM Admin tool, here is how to use it."
Statement39 <- "Design your model."
Statement40 <- "Find some experts to help you evaluate the model."
Statement41 <- "Send your experts an evaluation to weight your options."
Statement42 <- "Use the results for your research."
Statement43 <- "My Models"
Statement44 <- "Before you do anything enter your email and a pin that you will remember on the My Models screen. Everything you save in the tool will be associated with that email and that pin. If you don't have anything in the field when you save it you will probably loose your work!"
Statement45 <- "Model Designer"
Statement46 <- "The model designer has 2 parts, the visual model as a tree and the form on the left to design the model. If you want to see a quick example just click the 'Load Example' button to see what the form and tree look like with a small model."
Statement47 <- "To create a model first you need a name and decision. The first level of the tree is your criteria. Note that this is a comma seperated list of criteria, so to add more criteria simply add a comma and the next criteria and click 'rebuild tree from form'."
Statement48 <- "Once your first level is set you can add sub critiera by adding comma seperated elements for each critiera. Every time you add some new elements just click the 'rebuild tree from form' button again to see your model as a tree. For each level in the tree you add you'll see a new tab on the form that you can click on and update."
Statement49 <- "The bottom of the form has Alternatives which are recommended but not required. In whatever you're trying to decide the alternatives are the different choices."
Statement50 <- "Experts"
Statement51 <- "The Experts tab is where you can manage your experts. To add a new expert put in the email of the expert and click 'Add New'. When you're done make sure you click the 'Update Experts' button too. If you need to update an experts email just change it and click update experts."
Statement52 <- "Each expert will get a unique URL to use to evaluate the model you've created. When you add an expert the link will shown under the expert, make sure you send that URL to the expert to evaluate the model to ensure results are collected accurately."
Statement53 <- "Evaluation Form"
Statement54 <- "Once you have designed a model the evaluation form is generated. This is for you to see what your experts see, it won't actually evaluate anything. You can also click on the links on the expert tab to see what experts will see."
Statement55 <- "Results"
Statement56 <- "Once your model has been evaluated results will be here."
Statement57 <- "Saved Models"
Statement58 <- "As you're working on a model you should be saving it. To load a model just got to this tab, enter the email and pin you used to save the model, and load it up."
